package eideia

object CountryCodes {

    val codeMap: Map[String,List[String]] = Map(
        "AD" -> List("Andorra","Andorra","Andorra","Andorra"),
        "AE" -> List("Emiratos Árabes Unidos","United Arab Emirates","Vereinigte Arabische Emirate","Unió dels Emirats Àrabs"),
        "AF" -> List("Afganistán","Afghanistan","Afghanistan","Afganistan"),
        "AG" -> List("Antigua y Barbuda","Antigua and Barbuda","Antigua und Barbuda","Antigua i Barbuda"),
        "AI" -> List("Anguila","Anguilla","Anguilla","Anguilla"),
        "AL" -> List("Albania","Albania","Albanien","Albània"),
        "AM" -> List("Armenia","Armenia","Armenien","Armènia"),
        "AN" -> List("Antillas Neerlandesas","Netherlands Antilles","Niederländische Antillen","Antilles Holandeses"),
        "AO" -> List("Angola","Angola","Angola","Angola"),
        "AR" -> List("Argentina","Argentina","Argentinien","Argentina"),
        "AT" -> List("Austria","Austria","Österreich","Àustria"),
        "AU" -> List("Australia","Australia","Australien","Austràlia"),
        "AW" -> List("Aruba","Aruba","Aruba","Aruba"),
        "AZ" -> List("Azerbaiyán","Azerbaijan","Aserbaidschan","Azerbaitjan"),
        "BA" -> List("Bosnia y Hercegovina","Bosnia and Herzegovina","Bosnien und Herzegowina","Bòsnia i Hercegovina"),
        "BB" -> List("Barbados","Barbados","Barbados","Barbados"),
        "BD" -> List("Bangladesh","Bangladesh","Bangladesch","Bangla Desh"),
        "BT" -> List("Bután","Bhutan","Bhutan","Bhutan"),
        "BE" -> List("Bélgica","Belgium","Belgien","Bèlgica"),
        "BF" -> List("Burkina Faso","Burkina Faso","Burkina Faso","Burkina Faso"),
        "BG" -> List("Bulgaria","Bulgaria","Bulgarien","Bulgària"),
        "BH" -> List("Bahráin","Bahrain","Bahrain","Bahrain"),
        "BI" -> List("Burundi","Burundi","Burundi","Burundi"),
        "BJ" -> List("Benín","Benin","Benin","Benín"),
        "BM" -> List("Bermudas","Bermuda","die Bermudas","Bermuda"),
        "BN" -> List("Brunéi","Brunei","Brunei Darussalam","Brunei"),
        "BO" -> List("Bolivia","Bolivia","Bolivien","Bolívia"),
        "BR" -> List("Brasil","Brazil","Brasilien","Brasil"),
        "BS" -> List("Bahamas","The Bahamas","Bahamas","Bahames"),
        "BW" -> List("Botsuana","Botswana","Botsuana","Botswana"),
        "BY" -> List("Bielorrusia","Belarus","Belarus","Bielorússia"),
        "BZ" -> List("Belice","Belize","Belize","Belize"),
        "CA" -> List("Canadá","Canada","Kanada","Canadà"),
        "CD" -> List("República Democrática del Congo","Democratic Republic of the Congo","Demokratische Republik Kongo","Congo, República Democràtica del"),
        "CF" -> List("República Centroafricana","Central African Republic","Zentralafrikanische Republik","República Centreafricana"),
        "CG" -> List("Congo","Congo","Kongo","Congo"),
        "CH" -> List("Suiza","Switzerland","Schweiz","Suïssa"),
        "CI" -> List("Costa de Marfil","Côte d'Ivoire","Côte d'Ivoire","Costa d'Ivori"),
        "CK" -> List("Islas Cook","Cook Islands","Cookinseln","Illes Cook"),
        "CL" -> List("Chile","Chile","Chile","Xile"),
        "CM" -> List("Camerún","Cameroon","Kamerun","Camerun"),
        "CN" -> List("China","China","China","Xina"),
        "CO" -> List("Colombia","Colombia","Kolumbien","Colòmbia"),
        "CR" -> List("Costa Rica","Costa Rica","Costa Rica","Costa Rica"),
        "RS" -> List("Serbia & Montenegro","Serbia & Montenegro","Serbien und Montenegro","Sèrbia i Montenegro"),
        "CU" -> List("Cuba","Cuba","Kuba","Cuba"),
        "CV" -> List("Cabo Verde","Cape Verde","Kap Verde","Cap Verd"),
        "CY" -> List("Chipre","Cyprus","Zypern","Xipre"),
        "CZ" -> List("República Checa","Czech Republic","Tschechische Republik","República Txeca"),
        "DE" -> List("Alemania","Germany","Deutschland","Alemanya"),
        "DJ" -> List("Yibuti","Djibouti","Dschibuti","Djibouti"),
        "DK" -> List("Dinamarca","Denmark","Dänemark","Dinamarca"),
        "DM" -> List("Dominica","Dominica","Dominica","Dominica"),
        "DO" -> List("República Dominicana","Dominican Republic","Dominikanische Republik","República Dominicana"),
        "DZ" -> List("Argelia","Algeria","Algerien","Algèria"),
        "EC" -> List("Ecuador","Ecuador","Ecuador","Equador"),
        "EE" -> List("Estonia","Estonia","Estland","Estònia"),
        "EG" -> List("Egipto","Egypt","Ägypten","Egipte"),
        "EH" -> List("Sáhara Occidental","Western Sahara","Westsahara","Sàhara Occidental"),
        "ER" -> List("Eritrea","Eritrea","Eritrea","Eritrea"),
        "ES" -> List("España","Spain","Spanien","Espanya"),
        "ET" -> List("Etiopía","Ethiopia","Äthiopien","Etiòpia"),
        "FI" -> List("Finlandia","Finland","Finnland","Finlàndia"),
        "FJ" -> List("Fiyi","Fiji","Fidschi","Fiji"),
        "FK" -> List("Islas Malvinas","Falkland Islands","Falklandinseln","Illes Malvines (Falkland)"),
        "FM" -> List("Micronesia","Micronesia","Mikronesien","Micronèsia, Estats Federats de"),
        "FO" -> List("Islas Feroe","Faeroe Islands","Färöer","Illes Fèroe"),
        "FR" -> List("Francia","France","Frankreich","França"),
        "GA" -> List("Gabón","Gabon","Gabun","Gabon"),
        "GB" -> List("Reino Unido","United Kingdom","Vereinigtes Königreich","Regne Unit"),
        "GD" -> List("Granada","Grenada","Grenada","Grenada"),
        "GE" -> List("Georgia","Georgia","Georgien","Geòrgia"),
        "GF" -> List("Guayana Francesa","French Guiana","Französisch-Guayana","Guaiana Francesa"),
        "GH" -> List("Ghana","Ghana","Ghana","Ghana"),
        "GI" -> List("Gibraltar","Gibraltar","Gibraltar","Gibraltar"),
        "GL" -> List("Groenlandia","Greenland","Grönland","Groenlàndia"),
        "GM" -> List("Gambia","The Gambia","Gambia","Gàmbia"),
        "GN" -> List("Guinea","Guinea","Guinea","Guinea"),
        "GP" -> List("Guadalupe","Guadeloupe","Guadeloupe","Guadalupe"),
        "GQ" -> List("Guinea Ecuatorial","Equatorial Guinea","Äquatorialguinea","Guinea Equatorial"),
        "GR" -> List("Grecia","Greece","Griechenland","Grècia"),
        "GT" -> List("Guatemala","Guatemala","Guatemala","Guatemala"),
        "GW" -> List("Guinea Bisau","Guinea-Bissa","Guinea-Bissa","Guinea Bissa"),
        "GY" -> List("Guyana","Guyana","Guyana","Guyana"),
        "HK" -> List("Hong Kong","Hong Kong","Hongkong","Hong Kong"),
        "HN" -> List("Honduras","Honduras","Honduras","Hondures"),
        "HR" -> List("Croacia","Croatia","Kroatien","Croàcia"),
        "HT" -> List("Haití","Haiti","Haiti","Haití"),
        "HU" -> List("Hungría","Hungary","Ungarn","Hongria"),
        "ID" -> List("Indonesia","Indonesia","Indonesien","Indonèsia"),
        "IE" -> List("Irlanda","Ireland","Irland","Irlanda"),
        "IL" -> List("Israel","Israel","Israel","Israel"),
        "IN" -> List("India (la)","India","Indien","Índia"),
        "IQ" -> List("Iraq","Iraq","Irak","Iraq"),
        "IR" -> List("Irán","Iran","Iran","Iran"),
        "IS" -> List("Islandia","Iceland","Island","Islàndia"),
        "IT" -> List("Italia","Italy","Italien","Itàlia"),
        "JM" -> List("Jamaica","Jamaica","Jamaika","Jamaica"),
        "JO" -> List("Jordania","Jordan","Jordanien","Jordània"),
        "JP" -> List("Japón","Japan","Japan","Japó"),
        "KE" -> List("Kenia","Kenya","Kenia","Kenya"),
        "KG" -> List("Kirguizistán","Kyrgyzstan","Kirgisistan","Kirguizistan"),
        "KH" -> List("Camboya","Cambodia","Kambodscha","Cambodja"),
        "KI" -> List("Kiribati","Kiribati","Kiribati","Kiribati"),
        "KM" -> List("Comoras","Comoros","Komoren","Comores"),
        "KN" -> List("San Cristóbal y Nieves","Saint Kitts and Nevis","St. Kitts und Nevis","Saint Christopher i Nevis"),
        "KP" -> List("Corea del Norte","North Korea","Demokratische Volksrepublik Korea","Corea del Nord"),
        "KR" -> List("Corea del Sur","South Korea","Republik Korea","Corea del Sud"),
        "KW" -> List("Kuwait","Kuwait","Kuwait","Kuwait"),
        "KY" -> List("Islas Caimán","Cayman Islands","Kaimaninseln","Illes Caiman"),
        "KZ" -> List("Kazajistán","Kazakhstan","Kasachstan","Kazakhstan"),
        "LA" -> List("Laos","Laos","Laos","Laos"),
        "LB" -> List("Líbano","Lebanon","Libanon","Líban"),
        "LC" -> List("Santa Lucía","Saint Lucia","St. Lucia","Saint Lucia"),
        "LI" -> List("Liechtenstein","Liechtenstein","Liechtenstein","Liechtenstein"),
        "LK" -> List("Sri Lanka","Sri Lanka","Sri Lanka","Sri Lanka"),
        "LR" -> List("Liberia","Liberia","Liberia","Libèria"),
        "LS" -> List("Lesoto","Lesotho","Lesotho","Lesotho"),
        "LT" -> List("Lituania","Lithuania","Litauen","Lituània"),
        "LU" -> List("Luxemburgo","Luxembourg ","Luxemburg","Luxemburg"),
        "LV" -> List("Letonia","Latvia","Lettland","Letònia"),
        "LY" -> List("Libia","Libya","Libyen","Líbia"),
        "MA" -> List("Marruecos","Morocco","Marokko","Marroc"),
        "MC" -> List("Mónaco","Monaco","Monaco","Mònaco"),
        "MD" -> List("Moldavia","Moldova","Republik Molda","Moldàvia"),
        "MG" -> List("Madagascar","Madagascar","Madagaskar","Madagascar"),
        "MH" -> List("Islas Marshall","Marshall Islands","Marshallinseln","Illes Marshall"),
        "MK" -> List("Macedonia","Republic of Macedonia","Republik Mazedonien","Macedònia"),
        "ML" -> List("Malí","Mali","Mali","Mali"),
        "MM" -> List("Birmania; Myanmar","Myanmar","Myanmar","Myanmar"),
        "MN" -> List("Mongolia","Mongolia","Mongolei","Mongòlia"),
        "MQ" -> List("Martinica","Martinique","Martinique","Martinica"),
        "MR" -> List("Mauritania","Mauritania","Mauretanien","Mauritània"),
        "MS" -> List("Montserrat","Montserrat","Montserrat","Montserrat"),
        "MT" -> List("Malta","Malta","Malta","Malta"),
        "MU" -> List("Mauricio","Mauritius","Mauritius","Maurici"),
        "MV" -> List("Maldivas","Maldives","Malediven","Maldives"),
        "MW" -> List("Malaui","Malawi","Malawi","Malawi"),
        "MX" -> List("México","Mexico","Mexiko","Mèxic"),
        "MY" -> List("Malasia","Malaysia","Malaysia","Malàisia"),
        "MZ" -> List("Mozambique","Mozambique","Mosambik","Moçambic|"),
        "NA" -> List("Namibia","Namibia","Namibia","Namíbia"),
        "NC" -> List("Nueva Caledonia","New Caledonia","Neukaledonien","Nova Caledònia"),
        "NE" -> List("Níger","Niger","Niger","Níger"),
        "NF" -> List("Isla Norfolk","Norfolk Island","Norfolkinsel","Illa Norfolk"),
        "NG" -> List("Nigeria","Nigeria","Nigeria","Nigèria"),
        "NI" -> List("Nicaragua","Nicaragua","Nicaragua","Nicaragua"),
        "NL" -> List("Países Bajos","Netherlands","Niederlande","Països Baixos"),
        "NO" -> List("Noruega","Norway","Norwegen","Noruega"),
        "NP" -> List("Nepal","Nepal","Nepal","Nepal"),
        "NR" -> List("Naur","Naur","Naur","Naur"),
        "NU" -> List("Niue","Niue","Niue","Niue"),
        "NZ" -> List("Nueva Zelanda","New Zealand","Neuseeland","Nova Zelanda"),
        "OM" -> List("Omán","Oman","Oman","Oman"),
        "PA" -> List("Panamá","Panama","Panama","Panamà"),
        "PE" -> List("Perú","Per","Per","Perú"),
        "PF" -> List("Polinesia Francesa","French Polynesia","Französisch-Polynesien","Polinèsia Francesa"),
        "PG" -> List("Papúa-Nueva Guinea","Papua New Guinea","Papua-Neuguinea","Papua Nova Guinea"),
        "PH" -> List("Filipinas","Philippines","Philippinen","Filipines"),
        "PK" -> List("Pakistán","Pakistan","Pakistan","Pakistan"),
        "PL" -> List("Polonia","Poland","Polen","Polònia"),
        "PM" -> List("San Pedro y Miquelón","Saint Pierre and Miquelon","St. Pierre und Miquelon","Saint Pierre i Miquelon"),
        "PS" -> List("Palestina","Palestine","Palestine","Palestina"),
        "PT" -> List("Portugal","Portugal","Portugal","Portugal"),
        "PW" -> List("Palaos","Pala","Pala","Pala"),
        "PY" -> List("Paraguay","Paraguay","Paraguay","Paraguai"),
        "QA" -> List("Qatar","Qatar","Katar","Qatar"),
        "RE" -> List("Reunión","Reunion","Reunion","Reunion"),
        "RO" -> List("Rumanía","Romania","Rumänien","Romania"),
        "RU" -> List("Rusia","Russia","Russische Föderation","Rússia"),
        "RW" -> List("Ruanda","Rwanda","Ruanda","Rwanda"),
        "SA" -> List("Arabia Saudí","Saudi Arabia","Saudi-Arabien","Aràbia Saudita"),
        "SB" -> List("Islas Salomón","Solomon Islands","Salomonen","Illes Salomó"),
        "SC" -> List("Seychelles","Seychelles","Seychellen","Seychelles"),
        "SD" -> List("Sudán","Sudan","Sudan","Sudan"),
        "SE" -> List("Suecia","Sweden","Schweden","Suècia"),
        "SG" -> List("Singapur","Singapore","Singapur","Singapur"),
        "SH" -> List("Santa Helena","Saint Helena","St. Helena","Saint Helena"),
        "SI" -> List("Eslovenia","Slovenia","Slowenien","Eslovènia"),
        "SK" -> List("Eslovaquia","Slovakia","Slowakei","Eslovàquia"),
        "SL" -> List("Sierra Leona","Sierra Leone","Sierra Leone","Sierra Leone"),
        "SM" -> List("San Marino","San Marino","San Marino","San Marino"),
        "SN" -> List("Senegal","Senegal","Senegal","Senegal"),
        "SO" -> List("Somalia","Somalia","Somalia","Somàlia"),
        "SR" -> List("Surinam","Suriname","Suriname","Surinam"),
        "ST" -> List("Santo Tomé y Príncipe","São Tomé and Príncipe","São Tomé und Príncipe","Sao Tomé i Príncipe"),
        "SV" -> List("El Salvador","El Salvador","El Salvador","El Salvador"),
        "SY" -> List("Siria","Syria","Syrien","Síria"),
        "SZ" -> List("Suazilandia","Swaziland","Swasiland","Swazilàndia"),
        "TC" -> List("Islas Turcas y Caicos","Turks and Caicos Islands","Turks- und Caicosinseln","Illes Turks i Caicos"),
        "TD" -> List("Chad","Chad","Tschad","Txad"),
        "TF" -> List("Territorios Australes Franceses","French Southern Territories","Französische Gebiete (Ind. Oz.)","Territoris Francesos del Sud"),
        "TG" -> List("Togo","Togo","Togo","Togo"),
        "TH" -> List("Tailandia","Thailand","Thailand","Tailàndia"),
        "TJ" -> List("Tayikistán","Tajikistan","Tadschikistan","Tadjikistan"),
        "TK" -> List("Tokela","Tokela","Tokela","Tokela"),
        "TL" -> List("Timor Oriental","East Timor","Osttimor","Timor-Leste"),
        "TM" -> List("Turkmenistán","Turkmenistan","Turkmenistan","Turkmenistan"),
        "TN" -> List("Túnez","Tunisia","Tunesien","Tunísia"),
        "TO" -> List("Tonga","Tonga","Tonga","Tonga"),
        "TR" -> List("Turquía","Turkey","Türkei","Turquia"),
        "TT" -> List("Trinidad y Tobago","Trinidad and Tobago","Trinidad und Tobago","Trinitat i Tobago"),
        "TV" -> List("Tuval","Tuval","Tuval","Tuval"),
        "TW" -> List("Taiwán","Taiwan","Taiwan","Taiwan"),
        "TZ" -> List("Tanzania","Tanzania","Tansania","Tanzània"),
        "UA" -> List("Ucrania","Ukraine","Ukraine","Ucraïna"),
        "UG" -> List("Uganda","Uganda","Uganda","Uganda"),
        "UY" -> List("Uruguay","Uruguay","Uruguay","Uruguai"),
        "UZ" -> List("Uzbekistán","Uzbekistan","Usbekistan","Uzbekistan"),
        "VA" -> List("El Vaticano","Vatican City","Vatikanstadt","Ciutat del Vaticà"),
        "VC" -> List("San Vicente y las Granadinas","Saint Vincent and the Grenadines","St. Vincent und die Grenadinen","Saint Vincent i les Grenadines"),
        "VE" -> List("Venezuela","Venezuela","Venezuela","Veneçuela"),
        "VG" -> List("Islas Vírgenes Británicas","British Virgin Islands","Britische Jungferninseln","Illes Verge Britàniques"),
        "VN" -> List("Vietnam","Vietnam","Vietnam","Vietnam"),
        "VU" -> List("Vanuat","Vanuat","Vanuat","Vanuat"),
        "WF" -> List("Wallis y Futuna","Wallis and Futuna","Wallis und Futuna","Wallis i Futuna"),
        "WS" -> List("Samoa","Samoa","Samoa","Samoa"),
        "YE" -> List("Yemen","Yemen","Jemen","Iemen"),
        "YT" -> List("Mayotte","Mayotte","Mayotte","Mayotte"),
        "ZA" -> List("Sudáfrica","South Africa","Südafrika","Sud-àfrica"),
        "ZM" -> List("Zambia","Zambia","Sambia","Zàmbia"),
        "ZW" -> List("Zimbabue","Zimbabwe","Simbabwe","Zimbabwe"),
        "AQ" -> List("Antártida","Antarctica", "Antarktika", "Antàrtida"),
        "AS" -> List("Samoa Americana", "American Samoa","Amerikanisch-Samoa","Samoa Nord-americana"),
        "AX" -> List("Islan Aran", "Aland Islands","Aran-Inseln","Illes Aran"),
        "PR" -> List("Puerto Rico","Puerto Rico","Puerto Rico","Puerto Rico"),
        "US" -> List("Estados Unidos", "United States", "Vereinigte Staaten", "Estats Units d'Amèrica"),
        "XK" -> List("Kosovo","Kosovo","Kosovo","Kosovo"),
        "ME" -> List("Montenegro","Montenegro","Montenegro","Montenegro")
        )

    val fipToIso: Map[String,String] = Map(
        "AA" -> "AW",
        "AC" -> "AG",
        "AE" -> "AE",
        "AF" -> "AF",
        "AG" -> "DZ",
        "AJ" -> "AZ",
        "AL" -> "AL",
        "AM" -> "AM",
        "AN" -> "AD",
        "AO" -> "AO",
        "AQ" -> "AS",
        "AR" -> "AR",
        "AS" -> "AU",
        "AU" -> "AT",
        "AV" -> "AI",
        "AY" -> "AQ",
        "BA" -> "BH",
        "BB" -> "BB",
        "BC" -> "BW",
        "BD" -> "BM",
        "BE" -> "BE",
        "BF" -> "BS",
        "BG" -> "BD",
        "BH" -> "BZ",
        "BK" -> "BA",
        "BL" -> "BO",
        "BM" -> "MM",
        "BN" -> "BJ",
        "BO" -> "BY",
        "BP" -> "SB",
        "BR" -> "BR",
        "BT" -> "BT",
        "BU" -> "BG",
        "BX" -> "BN",
        "BY" -> "BI",
        "CA" -> "CA",
        "CB" -> "KH",
        "CD" -> "TD",
        "CE" -> "LK",
        "CF" -> "CG",
        "CG" -> "CD",
        "CH" -> "CN",
        "CI" -> "CL",
        "CJ" -> "KY",
        "CM" -> "CM",
        "CN" -> "KM",
        "CO" -> "CO",
        "CS" -> "CR",
        "CT" -> "CF",
        "CU" -> "CU",
        "CV" -> "CV",
        "CW" -> "CK",
        "CY" -> "CY",
        "DA" -> "DK",
        "DJ" -> "DJ",
        "DO" -> "DM",
        "DR" -> "DO",
        "EC" -> "EC",
        "EG" -> "EG",
        "EI" -> "IE",
        "EK" -> "GQ",
        "EN" -> "EE",
        "ER" -> "ER",
        "ES" -> "SV",
        "ET" -> "ET",
        "EZ" -> "CZ",
        "FG" -> "GF",
        "FI" -> "FI",
        "FJ" -> "FJ",
        "FK" -> "FK",
        "FM" -> "FM",
        "FO" -> "FO",
        "FP" -> "PF",
        "FR" -> "FR",
        "FS" -> "TF",
        "GA" -> "GM",
        "GB" -> "GA",
        "GG" -> "GE",
        "GH" -> "GH",
        "GI" -> "GI",
        "GJ" -> "GD",
        "GL" -> "GL",
        "GM" -> "DE",
        "GP" -> "GP",
        "GR" -> "GR",
        "GT" -> "GT",
        "GV" -> "GN",
        "GY" -> "GY",
        "HA" -> "HT",
        "HK" -> "HK",
        "HO" -> "HN",
        "HR" -> "HR",
        "HU" -> "HU",
        "IC" -> "IS",
        "ID" -> "ID",
        "IN" -> "IN",
        "IR" -> "IR",
        "IS" -> "IL",
        "IT" -> "IT",
        "IV" -> "CI",
        "IZ" -> "IQ",
        "JA" -> "JP",
        "JM" -> "JM",
        "JO" -> "JO",
        "KE" -> "KE",
        "KG" -> "KG",
        "KN" -> "KP",
        "KR" -> "KI",
        "KS" -> "KR",
        "KU" -> "KW",
        "KV" -> "XK",
        "KZ" -> "KZ",
        "LA" -> "LA",
        "LE" -> "LB",
        "LG" -> "LV",
        "LH" -> "LT",
        "LI" -> "LR",
        "LO" -> "SK",
        "LS" -> "LI",
        "LT" -> "LS",
        "LU" -> "LU",
        "LY" -> "LY",
        "MA" -> "MG",
        "MB" -> "MQ",
        "MD" -> "MD",
        "MF" -> "YT",
        "MG" -> "MN",
        "MH" -> "MS",
        "MI" -> "MW",
        "MJ" -> "ME",
        "MK" -> "MK",
        "ML" -> "ML",
        "MN" -> "MC",
        "MO" -> "MA",
        "MP" -> "MU",
        "MR" -> "MR",
        "MT" -> "MT",
        "MU" -> "OM",
        "MV" -> "MV",
        "MX" -> "MX",
        "MY" -> "MY",
        "MZ" -> "MZ",
        "NC" -> "NC",
        "NE" -> "NU",
        "NF" -> "NF",
        "NG" -> "NE",
        "NH" -> "VU",
        "NI" -> "NG",
        "NL" -> "NL",
        "NO" -> "NO",
        "NP" -> "NP",
        "NR" -> "NR",
        "NS" -> "SR",
        "NT" -> "AN",
        "NU" -> "NI",
        "NZ" -> "NZ",
        "PA" -> "PY",
        "PE" -> "PE",
        "PK" -> "PK",
        "PL" -> "PL",
        "PM" -> "PA",
        "PO" -> "PT",
        "PP" -> "PG",
        "PS" -> "PW",
        "PU" -> "GW",
        "QA" -> "QA",
        "RE" -> "RE",
        "RI" -> "RS",
        "RM" -> "MH",
        "RO" -> "RO",
        "RP" -> "PH",
        "RQ" -> "PR",
        "RS" -> "RU",
        "RW" -> "RW",
        "SA" -> "SA",
        "SB" -> "PM",
        "SC" -> "KN",
        "SE" -> "SC",
        "SF" -> "ZA",
        "SG" -> "SN",
        "SH" -> "SH",
        "SI" -> "SI",
        "SL" -> "SL",
        "SM" -> "SM",
        "SN" -> "SG",
        "SO" -> "SO",
        "SP" -> "ES",
        "ST" -> "LC",
        "SU" -> "SD",
        "SW" -> "SE",
        "SY" -> "SY",
        "SZ" -> "CH",
        "TD" -> "TT",
        "TH" -> "TH",
        "TI" -> "TJ",
        "TK" -> "TC",
        "TL" -> "TK",
        "TN" -> "TO",
        "TO" -> "TG",
        "TP" -> "ST",
        "TS" -> "TN",
        "TT" -> "TL",
        "TU" -> "TR",
        "TV" -> "TV",
        "TW" -> "TW",
        "TX" -> "TM",
        "TZ" -> "TZ",
        "UG" -> "UG",
        "UK" -> "GB",
        "UP" -> "UA",
        "US" -> "US",
        "UV" -> "BF",
        "UY" -> "UY",
        "UZ" -> "UZ",
        "VC" -> "VC",
        "VE" -> "VE",
        "VI" -> "VG",
        "VM" -> "VN",
        "VT" -> "VA",
        "WA" -> "NA",
        "WE" -> "PS",
        "WF" -> "WF",
        "WI" -> "EH",
        "WS" -> "WS",
        "WZ" -> "SZ",
        "YM" -> "YE",
        "ZA" -> "ZM",
        "ZI" -> "ZW"
    )

}
//"BL ->TB" Saint Barthelemy
//"BQ ->  " Bonaire, Saint Eustatius and Saba
//"BV ->BV" Bouvet Island
//"CC ->CK" Cocos Islands
//"CW ->UC" Curacao
//"CX ->KT" Christmas Island
//"GG ->GK" Guernsey
//"GS ->SX" South Georgia and the South Sandwich Islands
//"GU ->GQ" Guam
//"HM ->HM" Heard Island and McDonald Islands
//"IM ->IM" Isle of Man
//"IO ->IO" British Indian Ocean Territory
//"JE ->JE" Jersey
//"MF ->RN" Saint Martin
//"MO ->MC" Macao
//"MP ->CQ" Northern Mariana Islands
//"PN ->PC" Pitcairn
//"SS ->OD" South Sudan
//"SJ ->SV" Svalbard and Jan Mayen
//"SX ->NN" Sint Maarten
//"UM ->  " United States Minor Outlying Islands
//"VI ->VQ" U.S. Virgin Islands
//"CS ->YI" Serbia and Montenegro
