package eideia.atlas

object CountryResolver {
    val langs = List("ES", "EN", "DE", "CA")

    def mapLocalizedCountryTocode(lang: String = "ES" ): Map[String,String] = {
        assert(langs.contains(lang))
        for ( (k,v) <- codeMap ) yield v(langs.indexOf(lang)) -> k
    }

    val codeMap = Map[String,List[String]](
        "AD" -> List[String]("Andorra","Andorra","Andorra","Andorra"),
        "AE" -> List[String]("Emiratos Árabes Unidos","United Arab Emirates","Vereinigte Arabische Emirate","Unió dels Emirats Àrabs"),
        "AF" -> List[String]("Afganistán","Afghanistan","Afghanistan","Afganistan"),
        "AG" -> List[String]("Antigua y Barbuda","Antigua and Barbuda","Antigua und Barbuda","Antigua i Barbuda"),
        "AI" -> List[String]("Anguila","Anguilla","Anguilla","Anguilla"),
        "AL" -> List[String]("Albania","Albania","Albanien","Albània"),
        "AM" -> List[String]("Armenia","Armenia","Armenien","Armènia"),
        "AN" -> List[String]("Antillas Neerlandesas","Netherlands Antilles","Niederländische Antillen","Antilles Holandeses"),
        "AO" -> List[String]("Angola","Angola","Angola","Angola"),
        "AR" -> List[String]("Argentina","Argentina","Argentinien","Argentina"),
        "AT" -> List[String]("Austria","Austria","Österreich","Àustria"),
        "AU" -> List[String]("Australia","Australia","Australien","Austràlia"),
        "AW" -> List[String]("Aruba","Aruba","Aruba","Aruba"),
        "AZ" -> List[String]("Azerbaiyán","Azerbaijan","Aserbaidschan","Azerbaitjan"),
        "BA" -> List[String]("Bosnia y Hercegovina","Bosnia and Herzegovina","Bosnien und Herzegowina","Bòsnia i Hercegovina"),
        "BB" -> List[String]("Barbados","Barbados","Barbados","Barbados"),
        "BD" -> List[String]("Bangladesh","Bangladesh","Bangladesch","Bangla Desh"),
        "BT" -> List[String]("Bután","Bhutan","Bhutan","Bhutan"),
        "BE" -> List[String]("Bélgica","Belgium","Belgien","Bèlgica"),
        "BF" -> List[String]("Burkina Faso","Burkina Faso","Burkina Faso","Burkina Faso"),
        "BG" -> List[String]("Bulgaria","Bulgaria","Bulgarien","Bulgària"),
        "BH" -> List[String]("Bahráin","Bahrain","Bahrain","Bahrain"),
        "BI" -> List[String]("Burundi","Burundi","Burundi","Burundi"),
        "BJ" -> List[String]("Benín","Benin","Benin","Benín"),
        "BM" -> List[String]("Bermudas","Bermuda","die Bermudas","Bermuda"),
        "BN" -> List[String]("Brunéi","Brunei","Brunei Darussalam","Brunei"),
        "BO" -> List[String]("Bolivia","Bolivia","Bolivien","Bolívia"),
        "BR" -> List[String]("Brasil","Brazil","Brasilien","Brasil"),
        "BS" -> List[String]("Bahamas","The Bahamas","Bahamas","Bahames"),
        "BW" -> List[String]("Botsuana","Botswana","Botsuana","Botswana"),
        "BY" -> List[String]("Bielorrusia","Belarus","Belarus","Bielorússia"),
        "BZ" -> List[String]("Belice","Belize","Belize","Belize"),
        "CA" -> List[String]("Canadá","Canada","Kanada","Canadà"),
        "CD" -> List[String]("República Democrática del Congo","Democratic Republic of the Congo","Demokratische Republik Kongo","Congo, República Democràtica del"),
        "CF" -> List[String]("República Centroafricana","Central African Republic","Zentralafrikanische Republik","República Centreafricana"),
        "CG" -> List[String]("Congo","Congo","Kongo","Congo"),
        "CH" -> List[String]("Suiza","Switzerland","Schweiz","Suïssa"),
        "CI" -> List[String]("Costa de Marfil","Côte d'Ivoire","Côte d'Ivoire","Costa d'Ivori"),
        "CK" -> List[String]("Islas Cook","Cook Islands","Cookinseln","Illes Cook"),
        "CL" -> List[String]("Chile","Chile","Chile","Xile"),
        "CM" -> List[String]("Camerún","Cameroon","Kamerun","Camerun"),
        "CN" -> List[String]("China","China","China","Xina"),
        "CO" -> List[String]("Colombia","Colombia","Kolumbien","Colòmbia"),
        "CR" -> List[String]("Costa Rica","Costa Rica","Costa Rica","Costa Rica"),
        "RS" -> List[String]("Serbia & Montenegro","Serbia & Montenegro","Serbien und Montenegro","Sèrbia i Montenegro"),
        "CU" -> List[String]("Cuba","Cuba","Kuba","Cuba"),
        "CV" -> List[String]("Cabo Verde","Cape Verde","Kap Verde","Cap Verd"),
        "CY" -> List[String]("Chipre","Cyprus","Zypern","Xipre"),
        "CZ" -> List[String]("República Checa","Czech Republic","Tschechische Republik","República Txeca"),
        "DE" -> List[String]("Alemania","Germany","Deutschland","Alemanya"),
        "DJ" -> List[String]("Yibuti","Djibouti","Dschibuti","Djibouti"),
        "DK" -> List[String]("Dinamarca","Denmark","Dänemark","Dinamarca"),
        "DM" -> List[String]("Dominica","Dominica","Dominica","Dominica"),
        "DO" -> List[String]("República Dominicana","Dominican Republic","Dominikanische Republik","República Dominicana"),
        "DZ" -> List[String]("Argelia","Algeria","Algerien","Algèria"),
        "EC" -> List[String]("Ecuador","Ecuador","Ecuador","Equador"),
        "EE" -> List[String]("Estonia","Estonia","Estland","Estònia"),
        "EG" -> List[String]("Egipto","Egypt","Ägypten","Egipte"),
        "EH" -> List[String]("Sáhara Occidental","Western Sahara","Westsahara","Sàhara Occidental"),
        "ER" -> List[String]("Eritrea","Eritrea","Eritrea","Eritrea"),
        "ES" -> List[String]("España","Spain","Spanien","Espanya"),
        "ET" -> List[String]("Etiopía","Ethiopia","Äthiopien","Etiòpia"),
        "FI" -> List[String]("Finlandia","Finland","Finnland","Finlàndia"),
        "FJ" -> List[String]("Fiyi","Fiji","Fidschi","Fiji"),
        "FK" -> List[String]("Islas Malvinas","Falkland Islands","Falklandinseln","Illes Malvines (Falkland)"),
        "FM" -> List[String]("Micronesia","Micronesia","Mikronesien","Micronèsia, Estats Federats de"),
        "FO" -> List[String]("Islas Feroe","Faeroe Islands","Färöer","Illes Fèroe"),
        "FR" -> List[String]("Francia","France","Frankreich","França"),
        "GA" -> List[String]("Gabón","Gabon","Gabun","Gabon"),
        "GB" -> List[String]("Gran Bretaña","United Kingdom","Vereinigtes Königreich","Regne Unit"),
        "GD" -> List[String]("Granada","Grenada","Grenada","Grenada"),
        "GE" -> List[String]("Georgia","Georgia","Georgien","Geòrgia"),
        "GF" -> List[String]("Guayana Francesa","French Guiana","Französisch-Guayana","Guaiana Francesa"),
        "GH" -> List[String]("Ghana","Ghana","Ghana","Ghana"),
        "GI" -> List[String]("Gibraltar","Gibraltar","Gibraltar","Gibraltar"),
        "GL" -> List[String]("Groenlandia","Greenland","Grönland","Groenlàndia"),
        "GM" -> List[String]("Gambia","The Gambia","Gambia","Gàmbia"),
        "GN" -> List[String]("Guinea","Guinea","Guinea","Guinea"),
        "GP" -> List[String]("Guadalupe","Guadeloupe","Guadeloupe","Guadalupe"),
        "GQ" -> List[String]("Guinea Ecuatorial","Equatorial Guinea","Äquatorialguinea","Guinea Equatorial"),
        "GR" -> List[String]("Grecia","Greece","Griechenland","Grècia"),
        "GT" -> List[String]("Guatemala","Guatemala","Guatemala","Guatemala"),
        "GW" -> List[String]("Guinea Bisau","Guinea-Bissa","Guinea-Bissa","Guinea Bissa"),
        "GY" -> List[String]("Guyana","Guyana","Guyana","Guyana"),
        "HK" -> List[String]("Hong Kong","Hong Kong","Hongkong","Hong Kong"),
        "HN" -> List[String]("Honduras","Honduras","Honduras","Hondures"),
        "HR" -> List[String]("Croacia","Croatia","Kroatien","Croàcia"),
        "HT" -> List[String]("Haití","Haiti","Haiti","Haití"),
        "HU" -> List[String]("Hungría","Hungary","Ungarn","Hongria"),
        "ID" -> List[String]("Indonesia","Indonesia","Indonesien","Indonèsia"),
        "IE" -> List[String]("Irlanda","Ireland","Irland","Irlanda"),
        "IL" -> List[String]("Israel","Israel","Israel","Israel"),
        "IN" -> List[String]("India","India","Indien","Índia"),
        "IQ" -> List[String]("Iraq","Iraq","Irak","Iraq"),
        "IR" -> List[String]("Irán","Iran","Iran","Iran"),
        "IS" -> List[String]("Islandia","Iceland","Island","Islàndia"),
        "IT" -> List[String]("Italia","Italy","Italien","Itàlia"),
        "JM" -> List[String]("Jamaica","Jamaica","Jamaika","Jamaica"),
        "JO" -> List[String]("Jordania","Jordan","Jordanien","Jordània"),
        "JP" -> List[String]("Japón","Japan","Japan","Japó"),
        "KE" -> List[String]("Kenia","Kenya","Kenia","Kenya"),
        "KG" -> List[String]("Kirguizistán","Kyrgyzstan","Kirgisistan","Kirguizistan"),
        "KH" -> List[String]("Camboya","Cambodia","Kambodscha","Cambodja"),
        "KI" -> List[String]("Kiribati","Kiribati","Kiribati","Kiribati"),
        "KM" -> List[String]("Comoras","Comoros","Komoren","Comores"),
        "KN" -> List[String]("San Cristóbal y Nieves","Saint Kitts and Nevis","St. Kitts und Nevis","Saint Christopher i Nevis"),
        "KP" -> List[String]("Corea del Norte","North Korea","Demokratische Volksrepublik Korea","Corea del Nord"),
        "KR" -> List[String]("Corea del Sur","South Korea","Republik Korea","Corea del Sud"),
        "KW" -> List[String]("Kuwait","Kuwait","Kuwait","Kuwait"),
        "KY" -> List[String]("Islas Caimán","Cayman Islands","Kaimaninseln","Illes Caiman"),
        "KZ" -> List[String]("Kazajistán","Kazakhstan","Kasachstan","Kazakhstan"),
        "LA" -> List[String]("Laos","Laos","Laos","Laos"),
        "LB" -> List[String]("Líbano","Lebanon","Libanon","Líban"),
        "LC" -> List[String]("Santa Lucía","Saint Lucia","St. Lucia","Saint Lucia"),
        "LI" -> List[String]("Liechtenstein","Liechtenstein","Liechtenstein","Liechtenstein"),
        "LK" -> List[String]("Sri Lanka","Sri Lanka","Sri Lanka","Sri Lanka"),
        "LR" -> List[String]("Liberia","Liberia","Liberia","Libèria"),
        "LS" -> List[String]("Lesoto","Lesotho","Lesotho","Lesotho"),
        "LT" -> List[String]("Lituania","Lithuania","Litauen","Lituània"),
        "LU" -> List[String]("Luxemburgo","Luxembourg ","Luxemburg","Luxemburg"),
        "LV" -> List[String]("Letonia","Latvia","Lettland","Letònia"),
        "LY" -> List[String]("Libia","Libya","Libyen","Líbia"),
        "MA" -> List[String]("Marruecos","Morocco","Marokko","Marroc"),
        "MC" -> List[String]("Mónaco","Monaco","Monaco","Mònaco"),
        "MD" -> List[String]("Moldavia","Moldova","Republik Molda","Moldàvia"),
        "MG" -> List[String]("Madagascar","Madagascar","Madagaskar","Madagascar"),
        "MH" -> List[String]("Islas Marshall","Marshall Islands","Marshallinseln","Illes Marshall"),
        "MK" -> List[String]("Macedonia","Republic of Macedonia","Republik Mazedonien","Macedònia"),
        "ML" -> List[String]("Malí","Mali","Mali","Mali"),
        "MM" -> List[String]("Birmania; Myanmar","Myanmar","Myanmar","Myanmar"),
        "MN" -> List[String]("Mongolia","Mongolia","Mongolei","Mongòlia"),
        "MQ" -> List[String]("Martinica","Martinique","Martinique","Martinica"),
        "MR" -> List[String]("Mauritania","Mauritania","Mauretanien","Mauritània"),
        "MS" -> List[String]("Montserrat","Montserrat","Montserrat","Montserrat"),
        "MT" -> List[String]("Malta","Malta","Malta","Malta"),
        "MU" -> List[String]("Mauricio","Mauritius","Mauritius","Maurici"),
        "MV" -> List[String]("Maldivas","Maldives","Malediven","Maldives"),
        "MW" -> List[String]("Malaui","Malawi","Malawi","Malawi"),
        "MX" -> List[String]("México","Mexico","Mexiko","Mèxic"),
        "MY" -> List[String]("Malasia","Malaysia","Malaysia","Malàisia"),
        "MZ" -> List[String]("Mozambique","Mozambique","Mosambik","Moçambic|"),
        "NA" -> List[String]("Namibia","Namibia","Namibia","Namíbia"),
        "NC" -> List[String]("Nueva Caledonia","New Caledonia","Neukaledonien","Nova Caledònia"),
        "NE" -> List[String]("Níger","Niger","Niger","Níger"),
        "NF" -> List[String]("Isla Norfolk","Norfolk Island","Norfolkinsel","Illa Norfolk"),
        "NG" -> List[String]("Nigeria","Nigeria","Nigeria","Nigèria"),
        "NI" -> List[String]("Nicaragua","Nicaragua","Nicaragua","Nicaragua"),
        "NL" -> List[String]("Países Bajos","Netherlands","Niederlande","Països Baixos"),
        "NO" -> List[String]("Noruega","Norway","Norwegen","Noruega"),
        "NP" -> List[String]("Nepal","Nepal","Nepal","Nepal"),
        "NR" -> List[String]("Naur","Naur","Naur","Naur"),
        "NU" -> List[String]("Niue","Niue","Niue","Niue"),
        "NZ" -> List[String]("Nueva Zelanda","New Zealand","Neuseeland","Nova Zelanda"),
        "OM" -> List[String]("Omán","Oman","Oman","Oman"),
        "PA" -> List[String]("Panamá","Panama","Panama","Panamà"),
        "PE" -> List[String]("Perú","Per","Per","Perú"),
        "PF" -> List[String]("Polinesia Francesa","French Polynesia","Französisch-Polynesien","Polinèsia Francesa"),
        "PG" -> List[String]("Papúa-Nueva Guinea","Papua New Guinea","Papua-Neuguinea","Papua Nova Guinea"),
        "PH" -> List[String]("Filipinas","Philippines","Philippinen","Filipines"),
        "PK" -> List[String]("Pakistán","Pakistan","Pakistan","Pakistan"),
        "PL" -> List[String]("Polonia","Poland","Polen","Polònia"),
        "PM" -> List[String]("San Pedro y Miquelón","Saint Pierre and Miquelon","St. Pierre und Miquelon","Saint Pierre i Miquelon"),
        "PS" -> List[String]("Palestina","Palestine","Palestine","Palestina"),
        "PT" -> List[String]("Portugal","Portugal","Portugal","Portugal"),
        "PW" -> List[String]("Palaos","Pala","Pala","Pala"),
        "PY" -> List[String]("Paraguay","Paraguay","Paraguay","Paraguai"),
        "QA" -> List[String]("Qatar","Qatar","Katar","Qatar"),
        "RE" -> List[String]("Reunión","Reunion","Reunion","Reunion"),
        "RO" -> List[String]("Rumanía","Romania","Rumänien","Romania"),
        "RU" -> List[String]("Rusia","Russia","Russische Föderation","Rússia"),
        "RW" -> List[String]("Ruanda","Rwanda","Ruanda","Rwanda"),
        "SA" -> List[String]("Arabia Saudí","Saudi Arabia","Saudi-Arabien","Aràbia Saudita"),
        "SB" -> List[String]("Islas Salomón","Solomon Islands","Salomonen","Illes Salomó"),
        "SC" -> List[String]("Seychelles","Seychelles","Seychellen","Seychelles"),
        "SD" -> List[String]("Sudán","Sudan","Sudan","Sudan"),
        "SE" -> List[String]("Suecia","Sweden","Schweden","Suècia"),
        "SG" -> List[String]("Singapur","Singapore","Singapur","Singapur"),
        "SH" -> List[String]("Santa Helena","Saint Helena","St. Helena","Saint Helena"),
        "SI" -> List[String]("Eslovenia","Slovenia","Slowenien","Eslovènia"),
        "SK" -> List[String]("Eslovaquia","Slovakia","Slowakei","Eslovàquia"),
        "SL" -> List[String]("Sierra Leona","Sierra Leone","Sierra Leone","Sierra Leone"),
        "SM" -> List[String]("San Marino","San Marino","San Marino","San Marino"),
        "SN" -> List[String]("Senegal","Senegal","Senegal","Senegal"),
        "SO" -> List[String]("Somalia","Somalia","Somalia","Somàlia"),
        "SR" -> List[String]("Surinam","Suriname","Suriname","Surinam"),
        "ST" -> List[String]("Santo Tomé y Príncipe","São Tomé and Príncipe","São Tomé und Príncipe","Sao Tomé i Príncipe"),
        "SV" -> List[String]("El Salvador","El Salvador","El Salvador","El Salvador"),
        "SY" -> List[String]("Siria","Syria","Syrien","Síria"),
        "SZ" -> List[String]("Suazilandia","Swaziland","Swasiland","Swazilàndia"),
        "TC" -> List[String]("Islas Turcas y Caicos","Turks and Caicos Islands","Turks- und Caicosinseln","Illes Turks i Caicos"),
        "TD" -> List[String]("Chad","Chad","Tschad","Txad"),
        "TF" -> List[String]("Territorios Australes Franceses","French Southern Territories","Französische Gebiete (Ind. Oz.)","Territoris Francesos del Sud"),
        "TG" -> List[String]("Togo","Togo","Togo","Togo"),
        "TH" -> List[String]("Tailandia","Thailand","Thailand","Tailàndia"),
        "TJ" -> List[String]("Tayikistán","Tajikistan","Tadschikistan","Tadjikistan"),
        "TK" -> List[String]("Tokela","Tokela","Tokela","Tokela"),
        "TL" -> List[String]("Timor Oriental","East Timor","Osttimor","Timor-Leste"),
        "TM" -> List[String]("Turkmenistán","Turkmenistan","Turkmenistan","Turkmenistan"),
        "TN" -> List[String]("Túnez","Tunisia","Tunesien","Tunísia"),
        "TO" -> List[String]("Tonga","Tonga","Tonga","Tonga"),
        "TR" -> List[String]("Turquía","Turkey","Türkei","Turquia"),
        "TT" -> List[String]("Trinidad y Tobago","Trinidad and Tobago","Trinidad und Tobago","Trinitat i Tobago"),
        "TV" -> List[String]("Tuval","Tuval","Tuval","Tuval"),
        "TW" -> List[String]("Taiwán","Taiwan","Taiwan","Taiwan"),
        "TZ" -> List[String]("Tanzania","Tanzania","Tansania","Tanzània"),
        "UA" -> List[String]("Ucrania","Ukraine","Ukraine","Ucraïna"),
        "UG" -> List[String]("Uganda","Uganda","Uganda","Uganda"),
        "UY" -> List[String]("Uruguay","Uruguay","Uruguay","Uruguai"),
        "UZ" -> List[String]("Uzbekistán","Uzbekistan","Usbekistan","Uzbekistan"),
        "VA" -> List[String]("El Vaticano","Vatican City","Vatikanstadt","Ciutat del Vaticà"),
        "VC" -> List[String]("San Vicente y las Granadinas","Saint Vincent and the Grenadines","St. Vincent und die Grenadinen","Saint Vincent i les Grenadines"),
        "VE" -> List[String]("Venezuela","Venezuela","Venezuela","Veneçuela"),
        "VG" -> List[String]("Islas Vírgenes Británicas","British Virgin Islands","Britische Jungferninseln","Illes Verge Britàniques"),
        "VN" -> List[String]("Vietnam","Vietnam","Vietnam","Vietnam"),
        "VU" -> List[String]("Vanuat","Vanuat","Vanuat","Vanuat"),
        "WF" -> List[String]("Wallis y Futuna","Wallis and Futuna","Wallis und Futuna","Wallis i Futuna"),
        "WS" -> List[String]("Samoa","Samoa","Samoa","Samoa"),
        "YE" -> List[String]("Yemen","Yemen","Jemen","Iemen"),
        "YT" -> List[String]("Mayotte","Mayotte","Mayotte","Mayotte"),
        "ZA" -> List[String]("Sudáfrica","South Africa","Südafrika","Sud-àfrica"),
        "ZM" -> List[String]("Zambia","Zambia","Sambia","Zàmbia"),
        "ZW" -> List[String]("Zimbabue","Zimbabwe","Simbabwe","Zimbabwe"),
        "AQ" -> List[String]("Antártida","Antarctica", "Antarktika", "Antàrtida"),
        "AS" -> List[String]("Samoa Americana", "American Samoa","Amerikanisch-Samoa","Samoa Nord-americana"),
        "AX" -> List[String]("Isla Aran", "Aland Islands", "Aran-Inseln", "Illes Aran"),
        "PR" -> List[String]("Puerto Rico","Puerto Rico","Puerto Rico","Puerto Rico"),
        "US" -> List[String]("Estados Unidos", "United States", "Vereinigte Staaten", "Estats Units d'Amèrica"),
        "XK" -> List[String]("Kosovo","Kosovo","Kosovo","Kosovo"),
        "ME" -> List[String]("Montenegro","Montenegro","Montenegro","Montenegro")
    )


//"BL ->TB" Saint Barthelemy
//"BQ ->  " Bonaire, Saint Eustatius and Saba
//"BV ->BV" Bouvet Island
//"CC ->CK" Cocos Islands
//"CW ->UC" Curacao
//"CX ->KT" Christmas Island
//"GG ->GK" Guernsey
//"GS ->SX" South Georgia and the South Sandwich Islands
//"GU ->GQ" Guam
//"HM ->HM" Heard Island and McDonald Islands
//"IM ->IM" Isle of Man
//"IO ->IO" British Indian Ocean Territory
//"JE ->JE" Jersey
//"MF ->RN" Saint Martin
//"MO ->MC" Macao
//"MP ->CQ" Northern Mariana Islands
//"PN ->PC" Pitcairn
//"SS ->OD" South Sudan
//"SJ ->SV" Svalbard and Jan Mayen
//"SX ->NN" Sint Maarten
//"UM ->  " United States Minor Outlying Islands
//"VI ->VQ" U.S. Virgin Islands
//"CS ->YI" Serbia and Montenegro

val fipToIso = Map[String,String](
    "AA" -> "AW",
    "AC" -> "AG",
    "AE" -> "AE",
    "AF" -> "AF",
    "AG" -> "DZ",
    "AJ" -> "AZ",
    "AL" -> "AL",
    "AM" -> "AM",
    "AN" -> "AD",
    "AO" -> "AO",
    "AQ" -> "AS",
    "AR" -> "AR",
    "AS" -> "AU",
    "AU" -> "AT",
    "AV" -> "AI",
    "AY" -> "AQ",
    "BA" -> "BH",
    "BB" -> "BB",
    "BC" -> "BW",
    "BD" -> "BM",
    "BE" -> "BE",
    "BF" -> "BS",
    "BG" -> "BD",
    "BH" -> "BZ",
    "BK" -> "BA",
    "BL" -> "BO",
    "BM" -> "MM",
    "BN" -> "BJ",
    "BO" -> "BY",
    "BP" -> "SB",
    "BR" -> "BR",
    "BT" -> "BT",
    "BU" -> "BG",
    "BX" -> "BN",
    "BY" -> "BI",
    "CA" -> "CA",
    "CB" -> "KH",
    "CD" -> "TD",
    "CE" -> "LK",
    "CF" -> "CG",
    "CG" -> "CD",
    "CH" -> "CN",
    "CI" -> "CL",
    "CJ" -> "KY",
    "CM" -> "CM",
    "CN" -> "KM",
    "CO" -> "CO",
    "CS" -> "CR",
    "CT" -> "CF",
    "CU" -> "CU",
    "CV" -> "CV",
    "CW" -> "CK",
    "CY" -> "CY",
    "DA" -> "DK",
    "DJ" -> "DJ",
    "DO" -> "DM",
    "DR" -> "DO",
    "EC" -> "EC",
    "EG" -> "EG",
    "EI" -> "IE",
    "EK" -> "GQ",
    "EN" -> "EE",
    "ER" -> "ER",
    "ES" -> "SV",
    "ET" -> "ET",
    "EZ" -> "CZ",
    "FG" -> "GF",
    "FI" -> "FI",
    "FJ" -> "FJ",
    "FK" -> "FK",
    "FM" -> "FM",
    "FO" -> "FO",
    "FP" -> "PF",
    "FR" -> "FR",
    "FS" -> "TF",
    "GA" -> "GM",
    "GB" -> "GA",
    "GG" -> "GE",
    "GH" -> "GH",
    "GI" -> "GI",
    "GJ" -> "GD",
    "GL" -> "GL",
    "GM" -> "DE",
    "GP" -> "GP",
    "GR" -> "GR",
    "GT" -> "GT",
    "GV" -> "GN",
    "GY" -> "GY",
    "HA" -> "HT",
    "HK" -> "HK",
    "HO" -> "HN",
    "HR" -> "HR",
    "HU" -> "HU",
    "IC" -> "IS",
    "ID" -> "ID",
    "IN" -> "IN",
    "IR" -> "IR",
    "IS" -> "IL",
    "IT" -> "IT",
    "IV" -> "CI",
    "IZ" -> "IQ",
    "JA" -> "JP",
    "JM" -> "JM",
    "JO" -> "JO",
    "KE" -> "KE",
    "KG" -> "KG",
    "KN" -> "KP",
    "KR" -> "KI",
    "KS" -> "KR",
    "KU" -> "KW",
    "KV" -> "XK",
    "KZ" -> "KZ",
    "LA" -> "LA",
    "LE" -> "LB",
    "LG" -> "LV",
    "LH" -> "LT",
    "LI" -> "LR",
    "LO" -> "SK",
    "LS" -> "LI",
    "LT" -> "LS",
    "LU" -> "LU",
    "LY" -> "LY",
    "MA" -> "MG",
    "MB" -> "MQ",
    "MD" -> "MD",
    "MF" -> "YT",
    "MG" -> "MN",
    "MH" -> "MS",
    "MI" -> "MW",
    "MJ" -> "ME",
    "MK" -> "MK",
    "ML" -> "ML",
    "MN" -> "MC",
    "MO" -> "MA",
    "MP" -> "MU",
    "MR" -> "MR",
    "MT" -> "MT",
    "MU" -> "OM",
    "MV" -> "MV",
    "MX" -> "MX",
    "MY" -> "MY",
    "MZ" -> "MZ",
    "NC" -> "NC",
    "NE" -> "NU",
    "NF" -> "NF",
    "NG" -> "NE",
    "NH" -> "VU",
    "NI" -> "NG",
    "NL" -> "NL",
    "NO" -> "NO",
    "NP" -> "NP",
    "NR" -> "NR",
    "NS" -> "SR",
    "NT" -> "AN",
    "NU" -> "NI",
    "NZ" -> "NZ",
    "PA" -> "PY",
    "PE" -> "PE",
    "PK" -> "PK",
    "PL" -> "PL",
    "PM" -> "PA",
    "PO" -> "PT",
    "PP" -> "PG",
    "PS" -> "PW",
    "PU" -> "GW",
    "QA" -> "QA",
    "RE" -> "RE",
    "RI" -> "RS",
    "RM" -> "MH",
    "RO" -> "RO",
    "RP" -> "PH",
    "RQ" -> "PR",
    "RS" -> "RU",
    "RW" -> "RW",
    "SA" -> "SA",
    "SB" -> "PM",
    "SC" -> "KN",
    "SE" -> "SC",
    "SF" -> "ZA",
    "SG" -> "SN",
    "SH" -> "SH",
    "SI" -> "SI",
    "SL" -> "SL",
    "SM" -> "SM",
    "SN" -> "SG",
    "SO" -> "SO",
    "SP" -> "ES",
    "ST" -> "LC",
    "SU" -> "SD",
    "SW" -> "SE",
    "SY" -> "SY",
    "SZ" -> "CH",
    "TD" -> "TT",
    "TH" -> "TH",
    "TI" -> "TJ",
    "TK" -> "TC",
    "TL" -> "TK",
    "TN" -> "TO",
    "TO" -> "TG",
    "TP" -> "ST",
    "TS" -> "TN",
    "TT" -> "TL",
    "TU" -> "TR",
    "TV" -> "TV",
    "TW" -> "TW",
    "TX" -> "TM",
    "TZ" -> "TZ",
    "UG" -> "UG",
    "UK" -> "GB",
    "UP" -> "UA",
    "US" -> "US",
    "UV" -> "BF",
    "UY" -> "UY",
    "UZ" -> "UZ",
    "VC" -> "VC",
    "VE" -> "VE",
    "VI" -> "VG",
    "VM" -> "VN",
    "VT" -> "VA",
    "WA" -> "NA",
    "WE" -> "PS",
    "WF" -> "WF",
    "WI" -> "EH",
    "WS" -> "WS",
    "WZ" -> "SZ",
    "YM" -> "YE",
    "ZA" -> "ZM",
    "ZI" -> "ZW"
    )
}
